export const DESCRIPTIONS = [
  "Toujours perdant",
  "Le Google ambulant",
  "Le roi de la devinette",
  "Le chanceux de service",
  "Le philosophe",
  "L'invocateur du Wi-Fi",
  "Le stratège incompris",
  "La fusée humaine",
  "Le suspense incarné",
  "Le devin",
  "Le distrait professionnel",
  "Le collectionneur de zéros",
  "Le joker",
  "Le coach motivant",
  "Le tricheur maladroit",
  "L'intello silencieux",
  "Le statistiquement improbable",
  "Le mec trop confiant",
  "L'érudit frustré",
  "Le touriste",
];
